### ISSUE TITLE
First time instructions for newbies should call out installing git and installing node

### ISSUE THREAD

**Issue by billwscott** [krakenjs/kraken-js#293]
Watching my 14 yr old daughter install kraken. Couple of issues came up:

* She of course didn't have node installed. Should we link out to it for newbies?
* She didn't have git installed. On MacOSX it tells you to install from XCode, but it is better to use the official git install (in my estimation). But regardless we should call out that installing kraken is dependent on having node installed and git installed.

**Comment by grawk** [comment]
What is **required** to work through the example is: 
* node
* npm
* [possibly] GCC/Python/Make (haven't tried without these available on my computer)

Git is not required, but obviously necessary for anyone who is going to start contributing or working on their own product.

I'm going to look for a good and stable document/blog post etc which we can link to in order to cover the prerequisites above. If such a document can be found it'd be better that we not try and maintain our own.

**Comment by grawk** [comment]
I'm inclined to close this. The krakenjs.com site now lists all the prerequisites to being able to use the kraken generator and work through the "Getting started" steps. Other framework/library sites implicitly assume git proficiency. I think we should do the same.
