### ISSUE TITLE
overriding routing configuration

### ISSUE THREAD

**Issue by rutaihwa** [krakenjs/kraken-js#345]
How to over ride routing configurations in case there are two or more server instances in a single kraken installation? Doing config.use does not override the default config.

**Comment by aredridel** [comment]
Which one are you referring to as the default?

I think the details of what you're trying to do matter a bunch here, so an example would help a ton.

**Comment by rutaihwa** [comment]
By default i mean `./controllers`

**Comment by aredridel** [comment]
You can configure an enrouten instance to point to any directory -- overriding the enrouten middleware in the config will let you change that.

What are you trying to do with two kraken instances in a single server that don't share controllers? What do they share?

**Comment by rutaihwa** [comment]
I have tried to configure like this on my app, `app.use(enrouten({ directory: 'routes' }));` it didnt seem to work..  I get `TypeError: number is not a function`.
They don't share most of stuff at the moment, just trying to understand the charm of kraken-js.

**Comment by aredridel** [comment]
When do you get that `TypeError`?

**Comment by rutaihwa** [comment]
When I do app.use();

**Comment by aredridel** [comment]
In kraken, you rarely do: you configure middleware in the `config.json` middleware key.

**Comment by aredridel** [comment]
So there's many parts to kraken-js.

If you're using app.use, you're bypassing the middleware-setup-as-configuration of confit and meddleware, so bypassing kraken to use enrouten directly. Nothing wrong with that per se, but it's a little off the beaten path.

Most kraken apps use `config.json`'s middleware key to list out the middleware to use -- the config file you write is merged with the default one inside the kraken-js package, so you can examine that to see the defaults clearly laid out. There's prerequisite stuff, then around priority 120 is the enrouten instance that loads the 'controllers' or route handler files, then after that is error handling and not-found middleware.

If you're configuring two separate apps, you'd probably want to use the sub-app approach where you mount one app on another with `app.use`, or use a single set of controllers and break the logic out into separate modules.

Kraken is still pretty flexible, but going off the beaten path is a little harder, since the point of kraken is to make it easier for bigger teams to work together coherently on a project and have it stay organized.

**Comment by rutaihwa** [comment]
Now I get the idea of what you are saying. I get the two altenative approaches you are proposing.
I saw that in kraken it is possible to override the config with `config.use()` / `config.set()` in  the onconfig .. why doesnt allow me to override the `middleware:router:module:arguments:directory`?

**Comment by aredridel** [comment]
Because you can just edit the config file ;-)

**Comment by aredridel** [comment]
(`config.set` is almost never needed or used.)

**Comment by rutaihwa** [comment]
Kraken way. :) Thanks

**Comment by aredridel** [comment]
Sure thing!
