### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by mikemliu** [krakenjs/kraken-js#349]
Is there a changelog document I can reference for updating kraken? For example, I am currently on `1.0.3` and need to update to `1.0.5` what general items should i watch out for?

I see a major migration document, but i'm mainly looking for changes between minor versions without having to do a diff on the release tags.

**Comment by jasisk** [comment]
No changelog to speak of since these have all been patch releases. We're quite strict about semver (a little too conservative, to be honest) so you can rest easy knowing things won't break.

That said, I've started adding detailed changelogs to releases in some of our other modules. It is my intention to continue this practice moving forward and will be applying this practice retroactively for kraken-js back to v1.0.0.

Informally, here are the changes impacting you:
##### 1.0.4
1. Add iojs and 0.12 to travis
2. Clean up the README a lot
3. Add a default favicon, disable it by default
4. 503 with a failure message if kraken fails to initialize
5. Sub-applications can inherit more settings from the parent application by setting the `inheritViews` option in the kraken options (default off)
6. Clean up express deprecation warnings
7. Optional 5xx error handling middleware logs the stack using debuglog with the `kraken/middleware/500` namespace
8. Dependency bumps (not developer-impacting)

##### 1.0.5
1. Add the option to provide an additional header to requests made while kraken is starting up (and 503ing)

**Comment by jasisk** [comment]
Closing this out but feel free to continue the conversation here.
