### ISSUE TITLE
How to create an HTTPS server in Kraken.js

### ISSUE THREAD

**Issue by realdog** [krakenjs/kraken-js#385]
I never found something 'about create HTTPS server in Krakenjs.com'，
Please tell me how to create HTTPS server in Kraken.js

**Comment by lmarkus** [comment]
It's not Kraken's responsibility to do this.
At the end of the day, Kraken lives on top of express, which in turn simply acts as a handler for Node's built in HTTPS server.

This is how you create a plain vanilla Node HTTPS Server:
[REF: https://nodejs.org/api/https.html#https_class_https_server ]

```javascript
var https = require('https');
var fs = require('fs');

var options = {
  key: fs.readFileSync('test/fixtures/keys/agent2-key.pem'),
  cert: fs.readFileSync('test/fixtures/keys/agent2-cert.pem')
};

https.createServer(options, function (req, res) {
  res.writeHead(200);
  res.end("hello world\n");
}).listen(8000);
```

Now if you look at a freshly generated kraken project, you'll see two files,
1.- `index.js`, which contains the setup for the kraken app
2.- `server.js` which contains the actual server initialization code.

The later is the one you're interested in:

```javascript
'use strict';

var app = require('./index');
var http = require('http');


var server;

/*
 * Create and start HTTP server.
 */

server = http.createServer(app);
server.listen(process.env.PORT || 8000);
server.on('listening', function () {
    console.log('Server listening on http://localhost:%d', this.address().port);
});
```

Compare this line `server = http.createServer(app);` with the similar one from the first code block. The only thing you need to do, is pass the appropriate keys within an `options` object.
(eg:  `server = http.createServer(options, app);` )

A neat trick here, is that instead of hardcoding the location of the certificates, like on the first example, you can make them part of the Kraken config files (So you get all the advantages of environment specific config), and then retrieve them using the `app.kraken.get('foo')` pattern.

So you can have a section in your config like:

```JSON
   "ssl":{
       "cert":"file://path/to/server.crt",
       "key":"file://path/to/privkey.pem"
   }
```

which can be retrieved as `app.kraken.get('ssl')`

Hope that helps!

**Comment by realdog** [comment]
Thank you very much!

**Comment by lmarkus** [comment]
You're welcome.
Don't forget to close the issue if you're done ;)

**Comment by jasisk** [comment]
Closing since this looks resolved. Feel free to keep up the discussion if necessary!

**Comment by alexsantos** [comment]
On a production environment you might want to use a proxy on top that would
do the job, like nginx.

Alex
Em 09/06/2015 22:46, "Jean-Charles Sisk" <notifications@github.com>
escreveu:
