### ISSUE TITLE
Kraken upgrade 2.0

### ISSUE THREAD

**Issue by lelea2** [krakenjs/kraken-js#427]
Hi,

I'm trying to upgrade my current app from kraken 1.x to 2.x and notice the servererror and filenotfound middleware becomes deprecated. I notice this is intentional https://github.com/krakenjs/kraken-js/issues/359. So, question, does that mean it is recommended to use other middleware for this feature? 

Is Kraken 2.x in its stable state for upgrade with node 4.2.x and npm3? Is there any doc for this major upgrade?

Thanks
Kareen

**Comment by jasisk** [comment]
Hi Kareen,

The idea behind deprecating those two middleware is that the default behavior in Express is generally sufficient (at least until it isn't*). The middleware that we shipped with kraken made too many assumptions (that there is a rendering engine, that xhr meant json, etc) and ended up, by and large, being more painful than helpful.

By default, Express (by means of [finalhandler](https://github.com/pillarjs/finalhandler)) will send a [blandly styled](https://github.com/pillarjs/finalhandler/blob/f047316418106bc8f6a573532d11df60de9b3543/index.js#L147-L155) 404 or 500 depending on whether or not an error is specified in the continuation—e.g., `next(error)`. If in production, [the rendered page does not include a stack trace](https://github.com/pillarjs/finalhandler/blob/fe4e4de9ebb0f3831493ad75119ee6ba40542853/index.js#L84-L86), otherwise it does (and, in every case besides the `test` environment, [the stack trace is printed to the console](https://github.com/strongloop/express/blob/2f8ac6726fa20ab5b4a05c112c886752868ac8ce/lib/application.js#L627-L630)).

In many, many cases, this is totally fine. If it's not fine, you can write your own handlers and stick them in the middleware pipeline. 404 and 500 handling tends two fall into two camps: one in which a simple default behavior is sufficient and one that requires a lot of custom handling. The included middleware just felt like it sat somewhere in the middle, so it is scheduled to be dropped.

As for your second question, kraken 2 is basically a drop-in replacement. A number of the dependencies have undergone dramatic refactoring but are, for the majority cases, functionally equivalent. For the minority cases, all of the breaking changes are documented in the [v2.0.0 release notes](https://github.com/krakenjs/kraken-js/releases/tag/v2.0.0) but, again, chances are the only change you'll have to make is `npm install --save kraken-js@latest`.

Closing but feel free to continue the discussion.

**Comment by lelea2** [comment]
Great thank you! 

Kareen
