### ISSUE TITLE
Kraken.js 404 and 500 middleware templates

### ISSUE THREAD

**Issue by killfish** [krakenjs/kraken-js#434]
I asked this question of stack but I haven't received any feedback: http://stackoverflow.com/questions/33961291/kraken-js-404-and-500-middleware-templates

Here's what I was asking

Is it possible to use different templates for 404 and 500 errors in a kraken.js application? Below is how you enable the middleware and tell it what template to use. For my application I need to use different templates depending on what section of the site the user is in.

```
"fileNotFound": {
  "enabled": true,
  "priority": 130,
  "module": {
    "name": "kraken-js/middleware/404",
    "arguments": ["tamarin/errors/404"]
  }
},
"serverError": {
  "enabled": true,
  "priority": 140,
  "module": {
    "name": "kraken-js/middleware/500",
    "arguments": ["tamarin/errors/500"]
  }
},
```
I could modify the middleware myself to accept multiple templates and some sort of logic to choose which template but I'm wondering if there is another solution.

**Comment by aredridel** [comment]
You can use the middlewares within specific routers, rather than app-wide.  That lets you specify different templates different places. A 404 handler is nothing more than a handler that you reach only when nothing else handles a request -- a final middleware.

A 500 is a bit trickier, but you can use the usual Express pattern of a four-argument middleware. It's little more than `res.status(500); res.render('errors/500')` as the body -- you can sprinkle that about pretty freely..

**Comment by killfish** [comment]
Ahhh, that's great. I ended up doing something like this for my route specific 404s and it works :)

```
var _404  = require('kraken-js/middleware/404');

module.exports = function(router) {

    router.get("/:lang?/*", _404('tamarin/admin/404'),  function(req, res) {
...
```
Thanks for your help!

**Comment by aredridel** [comment]
Sure thing!
