### ISSUE TITLE
How to have API versioning in KrakenJS?

### ISSUE THREAD

**Issue by vdogra** [krakenjs/kraken-js#439]
I'm planning to build a service in KrakenJS and expose some APIs for which I would like to have versioning. There is whole lot debate whether URI versioning should be there or not but anyway I decided to go ahead with it.

In KrakenJS, folder structure of insider controllers directly decide upon the API handlers.

I would like to have something like

[protocol]:[host]/api/v1/blah/
[protocol]:[host]/api/v2/blah/

Is there any best practice in KrakenJS to do it?

**Comment by lmarkus** [comment]
By default, Kraken maps the structure in your controllers folder to URL paths.

You could use this to your advantage if your API versioning will be done at path level:
eg:  
Let's say you have a `users` API with a `GET` operation that takes a user Id, which you access by hitting a URL like : `www.server.com/api/v1/users/12345`

Such an API can by serviced by a controller like:
```javascript
module.exports = function (router) {
    /**
     * Retrieve user info
     */
    router.get('/:userId', function (req, res) {
        res.send('I got user ID ' + req.params.userId);
    })
}
```

Your controllers folder could look like this in order to house two live version of this API:

```
controllers/
├── api
│   ├── v1
│   │   └── users.js    //mounts to: /api/v1/users/:userId
│   └── v2
│       └── users.js    //mounts to: /api/v2/users/:userId
│
└── index.js            //non-api, www content.
```

Ultimately, there are many ways to solve this problem.  Kraken doesn't have an "opinion" per se. The above is just one example.

**Comment by vdogra** [comment]
Awesome! Thanks @lmarkus
