### ISSUE TITLE
Not able to ignore CVS files

### ISSUE THREAD

**Issue by mailto-kkk** [krakenjs/kraken-js#440]
Hi,

I upgraded my kraken project to the version 2.0.1. After that my server is not able to start. It seems like the controller is looking inside the CVS folder also. I also configured .npmignore file, to ignore the CVS files, but still the issue persists.

If I delete the CVS folder, it is running fine.

@aredridel 

Thanks & Regards,
K.K.Kumaresan

**Comment by lmarkus** [comment]
can you post your folder structure, and you config file(s)?

**Comment by mailto-kkk** [comment]
Hi,

Please find the folder structure and the config files.

[config.json.txt](https://github.com/krakenjs/kraken-js/files/73795/config.json.txt)
[development.json.txt](https://github.com/krakenjs/kraken-js/files/73796/development.json.txt)
![folder_structure](https://cloud.githubusercontent.com/assets/16473926/12031942/a8a04782-ae4d-11e5-9a37-8792e13fc0f4.png)

Thanks for the help

**Comment by lmarkus** [comment]
The problem is on the [express-enrouten](https://github.com/krakenjs/express-enrouten) module, specifically here: https://github.com/krakenjs/express-enrouten/blob/v1.2.x-release/lib/directory.js#L101-L102

In order to support `require`able non-traditional file extensions, (eg: `thing.coffee`), the file extension is thrown away, and the file is checked using `require.resolve()`.

There are three scenarios here:

1. `controllerFile.js`:  Extension thrown out,  `/path/to/controllerFile` resolves as a module, since it can be matched to `controllerFile.js`. It will be processed.

2. `textFile.txt`: Extension thrown out, `path/to/textFile` This does not resolve as a module, since `require()` can't match it to `textFile`, `textFile.js`, `textFile.json` nor a directory with an `index.js file`. It will be ignored.

3. `fileWithNoExtension`: `/path/to/fileWithNoExtension` **resolves** as a module, because it can be matched to a valid existing file (just like the first case). It will be processed.

Case 3 is the one that gets you, since CVS stores extensionless files in its hidden directories (eg: `Entries`, `Repository`, `Root`).

Since I already did all the write-up, I'll just go ahead an file the bug on the express-enrouten side.

**Comment by lmarkus** [comment]
Non-helpful solution: Switch to Git :stuck_out_tongue_closed_eyes: 
Let's track this on the express-enrouten repo rather than here.

**Comment by mailto-kkk** [comment]
ok. Thanks Markus..

@lmarkus

**Comment by grawk** [comment]
looks like this should be tracked elsewhere if it's still a concern.
