### ISSUE TITLE
 {"whitespace": true}  doesn't work

### ISSUE THREAD

**Issue by realdog** [krakenjs/kraken-js#441]
When i use {{"whitespace": true} in this config ,it worked.
```
   "view engines": {
        "dust": {
            "module": "makara",
            "renderer": {
                "method": "dust",
                "arguments": [
                    { "cache": false, "helpers": "config:dust.helpers", "whitespace":true},
                    {
                        "views": "config:express.views",
                        "view engine": "config:express.view engine",
                        "specialization": "config:specialization",
                        "i18n": "config:i18n"
                    }
                ]
            }
        }
    }
```

But when i  use  {"whitespace": true} in this config...(i changed the module), it doesn't work, what should i do?
```
   "view engines": {
        "dust": {
            "module": "engine-munger",
            "renderer": {
                "method": "dust",
                "arguments": [
                    { "cache": false, "helpers": "config:dust.helpers", "whitespace":true},
                    {
                        "views": "config:express.views",
                        "view engine": "config:express.view engine",
                        "specialization": "config:specialization",
                        "i18n": "config:i18n"
                    }
                ]
            }
        }
    },
```

**Comment by grawk** [comment]
You'd be better off using `makara` as that's the module we will be supporting moving forward. It does use engine-munger under the hood. Also keep in mind that engine-munger has gone through breaking changes as we've moved to using makara. So, it may be possible to use engine-munger directly, provided you use the correct version. If possible, please go with the first approach as it will be easier for us to help you with it.

**Comment by grawk** [comment]
@realdog:

In order to get to the core of your issue, it will be necessary to know, for both of your configuration examples above, what versions of engine-munger and/or makara you have in the given application. Also, please provide more detail around what exactly doesn't work.

I used the latest kraken generator to make two applications. One uses the `makara@^2.0` module for view engine configuration (using `engine-munger@1.1.1`). The other uses `engine-munger@0.2.8` to configure the view engine.

In the "makara" application, toggling whitespace true/false does have the desired effect.

In the second application, toggling whitespace does not have an effect, but whitespace preservation appears to be the default.

So, from my investigation what I'd say "doesn't work" is the whitespace toggle when using dust via `engine-munger@~0.2`. Given that, there may be an issue in how engine-munger passes along the configuration to the dust engine. I will hold off on debugging further in, pending your response.

But once we can isolate what isn't working for you we will likely need to close this issue and open one on the appropriate module.

**Comment by realdog** [comment]
@grawk  Thank you very much.But when i use makara, i have there are some tag can't be used. for example: eq , i have no idea.....how to repaire this

**Comment by lmarkus** [comment]
@realdog In your `./config/config.json` file, you'll see a section like this:

```json
    "dust": {
        "helpers": [
    
            "dust-makara-helpers"
    
        ]
    },
```
You'll need to `npm i --save dustjs-helpers` and then simply add an entry into that array:

```json
    "dust": {
        "helpers": [

            "dustjs-helpers",    
            "dust-makara-helpers"
    
        ]
    },
```
Your helpers will be available then.
(The reason for this, is that newer versions of dust, don't bundle the helpers anymore. They need to be installed separately).

**Comment by realdog** [comment]
YEAH ~~~~
@lmarkus   It  worked.....thank u very much.

**Comment by lmarkus** [comment]
Cool. :+1: 
Don't forget to close the issue @realdog :)

**Comment by grawk** [comment]
Thanks @lmarkus for the help with that. Closing.
